name: Release Backend

on:
  push:
    tags:
      - allowlist-backend/*

jobs:
  release-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Docker Image
        uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@main
        with:
          SERVICE_NAME: allowlist-backend
          BUILD_ARGS: |
            build_image=node:18-slim
          DOCKER_FILE_PATH: backend/Dockerfile
          DOCKER_CONTEXT_PATH: backend
        secrets: inherit