[package]
name = "cis2-market"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concordium-std = { version = "8.0.0", default-features = false }
concordium-cis2 = { version = "5.0.0", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
opt-level = "s"
panic = "abort"

[profile.dev]
panic = "abort"

[features]
default = ["std"]
std = ["concordium-std/std", "concordium-cis2/std"]