name: Release Web3ID Verifier

on:
  push:
    tags:
      - allowlist-web3id-verifier/*

jobs:
  release-web3id-verifier:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@v1
    with:
      SERVICE_NAME: allowlist-web3id-verifier
      BUILD_ARGS: |
        build_image=node:18-slim
      DOCKER_FILE_PATH: allowListManagerFaucet/services/web3id-verifier-ts/Dockerfile
      DOCKER_CONTEXT: allowListManagerFaucet/services/web3id-verifier-ts
    secrets: inherit
