version: '3.8'

# This docker compose setup has the following important configuration options, which reside in the `.env` file.
# Namely the:
#  - The network to use (mainnet/testnet)
#  - The Concordium node gRPC endpoint (which should point at the correct net, e.g., mainnet or testnet)
#  - The contract address for the relevant track and trace contract
#  - The location of the private key file for the sponsor account

services:
  sponsored-transaction-service:
    build:
      context: .
      dockerfile: ./dockerfiles/sponsored-transaction-service.Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./private-keys:/private-keys
    environment:
      CCD_SPONSORED_TRANSACTION_SERVICE_ALLOWED_ACCOUNTS: Any
      CCD_SPONSORED_TRANSACTION_SERVICE_ALLOWED_CONTRACTS: ${TRACK_AND_TRACE_CONTRACT_ADDRESS}
      CCD_SPONSORED_TRANSACTION_SERVICE_PRIVATE_KEY_FILE: ${TRACK_AND_TRACE_PRIVATE_KEY_FILE}
      CCD_SPONSORED_TRANSACTION_SERVICE_LISTEN_ADDRESS: 0.0.0.0:8000
      CCD_SPONSORED_TRANSACTION_SERVICE_NODE: ${TRACK_AND_TRACE_NODE}

  server:
    build:
      context: .
      dockerfile: ./dockerfiles/server.Dockerfile
    restart: always
    environment:
      CCD_SERVER_DB_CONNECTION: "host=postgres dbname=indexer user=postgres password=password port=5432"
      CCD_SERVER_CONTRACT_ADDRESS: ${TRACK_AND_TRACE_CONTRACT_ADDRESS}
      CCD_SERVER_SPONSORED_TRANSACTION_BACKEND: "http://localhost:8000"
      CCD_SERVER_NETWORK: ${TRACK_AND_TRACE_NETWORK}
      CCD_SERVER_NODE: ${TRACK_AND_TRACE_NODE}
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - indexer

  indexer:
    build:
      context: .
      dockerfile: ./dockerfiles/indexer.Dockerfile
    restart: always
    environment:
      CCD_INDEXER_CONTRACT: ${TRACK_AND_TRACE_CONTRACT_ADDRESS}
      CCD_INDEXER_NODE: ${TRACK_AND_TRACE_NODE}
      CCD_INDEXER_DB_CONNECTION: "host=postgres dbname=indexer user=postgres password=password port=5432"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
