import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const satoshi = localFont({
  src: "./fonts/Satoshi-Regular.otf",
  variable: "--font-satoshi-sans",
  weight: "100 200 300 400 500 600 700 800 900",
});
// deployment
export const metadata: Metadata = {
  title: "Claim Reward - Concordium",
  description: "Generated by FISTA Solutions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
