name: Build Docker Containers

on:
  push:
    branches: main

  pull_request:
    branches: main
    paths:
      - 'euroe-demo/**'
      - 'signMessage/**'
      - 'simpleAgeVerification/**'
      - 'gallery/**' 
      - 'deps/concordium-rust-sdk'
      - 'sponsoredTransactions/**'
      - 'sponsoredTransactionsAuction/**'
      - '!**.md'

  workflow_dispatch: # allows manual trigger

# These get updated conditionally for specific apps
# The build process slightly differs between them.
env:
  DOCKER_DIR: '.'
  DOCKERFILE_DIR: '.'

jobs:
  changes:
    name: detect what files changed
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      directories: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for backend file changes for Docker builds
        uses: dorny/paths-filter@v3.0.2
        id: docker-changes
        with:
          filters: |
            euroe-demo:
              - 'euroe-demo/**'
            gallery:
              - 'gallery/**'
              - 'deps/concordium-rust-sdk'
            simpleAgeVerification:
              - 'simpleAgeVerification/**'
            signMessage:
              - 'signMessage/**'
            sponsoredTransactions:
              - 'sponsoredTransactions/**'
              - 'deps/concordium-rust-sdk'
            sponsoredTransactionsAuction:
              - 'sponsoredTransactionsAuction/**'
              - 'deps'

  build:
    name: Building Docker Containers
    # Require the diff job.
    needs: docker-changes
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # JSON array contains all directories with docker images and changed files
        # e.g. ['euroe-demo', 'signMessage'] if both package folders contains changes
        image: ${{ fromJSON(needs.docker-changes.outputs.directories) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build image
      working-directory: ${{ env.DOCKER_DIR }}
      run: |
        echo "${{ matrix.image }} is the matrix image to build"
  
    - name: Set the path to the docker build directory to the dapp name for some apps.
      if: ${{ contains(fromJson('["euroe-demo", "signMessage", "simpleAgeVerification"]'), matrix.image) }}
      run: |
        echo "DOCKER_DIR=./${{ matrix.image }}" >> $GITHUB_ENV

    - name: Set the path to the dockerfile to the scripts subdirectory for euroe-demo.
      if: ${{ contains(fromJson('["euroe-demo"]'), matrix.image) }}
      run: |
        echo "DOCKERFILE_DIR=./scripts" >> $GITHUB_ENV
  
    - name: Set the path to the dockerfile where it is the dapp name.
      if: ${{ contains(fromJson('["sponsoredTransactionsAuction", "sponsoredTransactions", "sponsoredTransactions"]'), matrix.image) }}
      run: |
        echo "DOCKERFILE_DIR=./${{ matrix.image }}" >> $GITHUB_ENV

    - name: Build image
      working-directory: ${{ env.DOCKER_DIR }}
      run: |
        echo "DOCKER_DIR is ${DOCKER_DIR}"
        echo "DOCKERFILE_DIR is ${DOCKERFILE_DIR}"
        docker build -f ${{ env.DOCKERFILE_DIR}}/Dockerfile .

  # compose-build:
  #   name: Building with docker compose
  #   # Don't run on draft pull requests
  #   if: ${{ !github.event.pull_request.draft }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       directories:
  #         - trackAndTrace
  #         - compliant-reward-distribution

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive

  #   - name: Build with docker compose
  #     working-directory: ${{ matrix.directories }}
  #     env:
  #       # Dummy values are set for the `trackAndTrace` run because `docker compose build`
  #       # enforces the presence of environment variables during the build phase,
  #       # even though these variables are only needed at runtime.
  #       TRACK_AND_TRACE_CONTRACT_ADDRESS: "<8351,0>"
  #       TRACK_AND_TRACE_PRIVATE_KEY_FILE: "./trackAndTrace/README.md"
  #     run:
  #       docker compose build
