name: Release Locks Frontend

on:
  push:
    tags:
      - locks-frontend/*

jobs:
  release-locks-frontend:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@v1
    with:
      SERVICE_NAME: rbac-frontend
      BUILD_ARGS: |
        base_image=node:18-slim
      DOCKER_FILE_PATH: locks/frontend/Dockerfile
      DOCKER_CONTEXT: locks/frontend
    secrets: inherit
