name: Release Frontend

on:
  push:
    tags:
      - allowlist-frontend/*

jobs:
  release-frontend:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@v1
    with:
      SERVICE_NAME: allowlist-frontend
      BUILD_ARGS: |
        build_image=node:18-slim
      DOCKER_FILE_PATH: allowListManagerFaucet/frontend/Dockerfile
      DOCKER_CONTEXT: allowListManagerFaucet/frontend
    secrets: inherit
