name: Release Frontend

on:
  push:
    tags:
      - allowlist-frontend/*

jobs:
  release-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Docker Image
        uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@main
        with:
          SERVICE_NAME: allowlist-frontend
          BUILD_ARGS: |
            build_image=node:18-slim
          DOCKER_FILE_PATH: allowListManagerFaucet/frontend/Dockerfile
          DOCKER_CONTEXT_PATH: allowListManagerFaucet/frontend
        secrets: inherit