# This job builds and publishes a docker image for the simple age verification dApp to
# the dockerhub image repository.
name: Create and publish a Docker image for the simple age verification dApp.

on:
  workflow_dispatch: # allows manual trigger

  push:
    tags:
      - 'simple-age-verification/*.*.*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: dapp-simple-age-verification
  EXPECTED_TAG: ${{ github.ref_name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: testnet-deployments
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # Uses the `docker/login-action` action to log in to the Container registry.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag from package.json
        id: meta
        run: |
          export VERSION=$(jq -r .version simpleAgeVerification/package.json)
          export FULL_IMAGE_TAG="${{ env.REGISTRY }}/concordium/$IMAGE_NAME:$VERSION"
          echo "::notice FULL_IMAGE_TAG=${FULL_IMAGE_TAG}"
          # Make sure the image does not exist. Abort if we can retrieve any metadata.
          if docker manifest inspect ${FULL_IMAGE_TAG} > /dev/null; then
             echo "::error ${FULL_IMAGE_TAG} already exists"
             exit 1
          elif [ ! "${EXPECTED_TAG}" = "simple-age-verification/${VERSION}" ]; then
             echo "::error Expected tag ${EXPECTED_TAG} does not match the version ${VERSION}."
             exit 1
          else
             # Store the full image tag into a tag variable for the following step.
             echo "tag=${FULL_IMAGE_TAG}" > "$GITHUB_OUTPUT"
          fi
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./simpleAgeVerification
          file: ./simpleAgeVerification/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tag }}
